### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lgatto** [lgatto/QSep-manuscript#3]
- [x] Replace hyperLOPIT MS2 with that Andreyev et al 2009 (see https://github.com/lgatto/pRolocdata/issues/15), but still use hyperLOPIT MS2 in figure 2, when introducing hexbin plots to assess cluster density
- [x] add more datasets
- [x] Finish section on Comparative study  
- [x] Finish Conclusions
- [x] Add citation/reference to each dataset
- [x] Add `Qsep` plots for all datasets
- [x] Is there a trend that newer datasets have better resolution?: I don't think so in general. Would be worth focusing on LOPIT experiments only.
